-- TEST ONLY: minimal empty contract schema, not a production migration.
-- No records, users, credentials, Storage or connections to Supabase are copied.
DO $$ BEGIN
 CREATE ROLE anon;
 CREATE ROLE authenticated;
 CREATE ROLE service_role;
END $$;
CREATE TABLE interventi (
 id bigserial PRIMARY KEY, data_intervento date, codice_cliente text, cliente text,
 struttura text, cartella_clinica text, chirurgo text, agente text, linea text,
 magazzino_scarico text
);
CREATE TABLE righe_intervento (
 id bigserial PRIMARY KEY, intervento_id bigint, codice text, descrizione text,
 lotto text, scadenza date, quantita numeric, produttore text, validazione text,
 prezzo numeric, totale numeric, valore numeric DEFAULT 0, prezzo_source text,
 origine text
);
CREATE TABLE giacenze (
 id bigserial PRIMARY KEY, codice_magazzino text NOT NULL, codice text NOT NULL,
 lotto text NOT NULL, scadenza date, quantita numeric DEFAULT 0,
 origine text DEFAULT 'CONTO DEPOSITO', updated_at timestamp DEFAULT now(),
 UNIQUE(codice_magazzino,codice,lotto,origine)
);
CREATE TABLE movimenti_magazzino (
 id bigserial PRIMARY KEY, data_movimento timestamp DEFAULT now(),
 tipo_movimento text NOT NULL, codice_magazzino text NOT NULL, codice text NOT NULL,
 descrizione text, lotto text NOT NULL, scadenza date, quantita numeric,
 origine text, riferimento_tipo text, riferimento_id text, note text, utente text
);
CREATE TABLE anomalie_giacenza (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codice text NOT NULL,
 lotto text, quantita_richiesta numeric NOT NULL DEFAULT 0,
 quantita_disponibile numeric NOT NULL DEFAULT 0, magazzino text,
 intervento_id bigint REFERENCES interventi(id) ON DELETE SET NULL,
 stato text NOT NULL DEFAULT 'DA_VERIFICARE', motivo text, creato_da text,
 risolto_da text, risolto_at timestamptz, created_at timestamptz DEFAULT now()
);
CREATE TABLE documenti_impianto (
 id bigserial PRIMARY KEY, intervento_id text, nome_file text
);
CREATE TABLE ddt_righe (id bigserial PRIMARY KEY);
CREATE TABLE kit_logistici (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE reintegri_kit (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 kit_id bigint NOT NULL REFERENCES kit_logistici(id) ON DELETE CASCADE,
 riga_intervento_id bigint REFERENCES righe_intervento(id) ON DELETE SET NULL,
 ddt_riga_id bigint REFERENCES ddt_righe(id) ON DELETE SET NULL,
 codice text NOT NULL, quantita_richiesta numeric NOT NULL DEFAULT 1,
 quantita_reintegrata numeric NOT NULL DEFAULT 0
);
CREATE TABLE audit_log (
 id bigserial PRIMARY KEY, utente text, azione text, tabella text,
 riferimento text, dettagli text
);

