[theme]
base="light"
primaryColor="#004AAD"
backgroundColor="#F7FAF9"
secondaryBackgroundColor="#EEF4F2"
textColor="#10262E"
font="sans serif"

[server]
maxUploadSize=200
enableStaticServing=true

[client]
toolbarMode="minimal"
